version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: capsule_db
      MYSQL_USER: capsule_user
      MYSQL_PASSWORD: retailpass
    ports:
      - "3306:3306"
   
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/0-init.sql

  retail-frontend:
  
    build: .
    container_name: retail-frontend
    ports:
      - "3016:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - retail_data:/usr/share/nginx/html  


volumes:
  mysql_data:
  retail_data:
